685 load data i dk5
DBCDK/dk5 pull request #774
Opened 2020-09-02 06:25 UTC by niwdbc

Ny Jenkinsfile til dataload flow, samt en rettelse i en anden Jenkinsfile der manglede at rydde op efter sig.

2020-09-02 10:08 UTC, vibjerg requested changes
Docker billedet bliver bygget to gange i pipelinen, og det bør ikke være nødvendigt. Jeg tror du lige skal se de andre pipelines i dette projekt igennem også, og sikre at det ikke sker generelt.

2020-09-02 10:08 UTC, vibjerg commented on pipelines/load-data-in-dk5/Jenkinsfile
> +                        ARTY_DOCKER.push("$DOCKER_NAME_LATEST", 'docker')
$DOCKER_NAME_LATEST bliver pushet 2 gange.

2020-09-02 10:08 UTC, vibjerg commented on pipelines/load-data-in-dk5/Jenkinsfile
> +                    docker image rm $DOCKER_NAME_LATEST
Hvis du underlader at bygge to gange, så behøver du heller ikke fjerne to gange

2020-09-02 11:18 UTC, niwdbc commented
> Docker billedet bliver bygget to gange i pipelinen, og det bør ikke være nødvendigt. Jeg tror du lige skal se de andre pipelines i dette projekt igennem også, og sikre at det ikke sker generelt.

OK. Jeg har gjort det samme i de andre pipelines. Dem retter jeg til efter samme metode.

2020-09-03 08:59 UTC, vibjerg approved these changes
💯

2020-09-03 09:07 UTC, merged